### ISSUE TITLE
Steel doesn't follow Windows audio output device changes

### ISSUE THREAD

**Issue by 0x84f** [TicClick/steel#57]
Example would be turning on steel while my speakers are set as the audio output device, then changing to my DAC. Steel will still output notification sounds to the speakers rather than the DAC.

Restart resolves this

**Comment by TicClick** [comment]
- https://github.com/RustAudio/rodio/issues/463
- https://github.com/RustAudio/rodio/issues/327

**Comment by TicClick** [comment]
this can probably be worked around if I take a look at https://github.com/ProjectAnni/anni/pull/39 and copy their homework (specifically, 00c54984b77863a451a15c88d823c919599dcac4 -- sorry pals)
